name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Deno (Unix)
        run: |-
          curl -fsSL https://deno.land/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Run linter
        run: make lint
      - name: Check formatting
        run: make fmt-check
      - name: Run tests
        run: make test
